### ISSUE TITLE
[Question] License of org.electronjs.Electron2.BaseApp

### ISSUE THREAD

**Issue by vhemery** [flathub/org.electronjs.Electron2.BaseApp#26]
Hello,
We would like to use this repository and re-compile it for offline usage.
Yet, I do not see a LICENSE / COPYING file and can't find the license of sources under this org.electronjs.Electron2.BaseApp repo.

Could you please tell me which license applies here ? ( and eventually add a LICENSE or COPYING file to the repo )

Thank you.

**Comment by bbhtt** [comment]
The manifest is just a build recipe. It's unclear that they can be licensed, see https://github.com/flathub/flathub/issues/2308. The software in the manifest and other files referenced in it can have their own licences.

@TingPing do you want a licence here?

**Comment by TingPing** [comment]
If it makes it more useful I don't mind.

I'd gladly put my contributions under the [CC0](https://creativecommons.org/public-domain/cc0/).

**Comment by TingPing** [comment]
It looks like a handful of others have made small changes though, so it becomes a hunt to license it.

**Comment by TingPing** [comment]
In the end I really do think, especially in the case of this package, everything is trivial and not copyrightable.

In a blind room everybody will come up with:

```yaml
  - name: libnotify
    buildsystem: meson
    config-opts:
      - -Dtests=false
      - -Dintrospection=disabled
      - -Dgtk_doc=false
      - -Ddocbook_docs=disabled
    sources:
      - type: archive
        url: https://download.gnome.org/sources/libnotify/0.7/libnotify-0.7.8.tar.xz
        sha256: 69209e0b663776a00c7b6c0e560302a8dbf66b2551d55616304f240bba66e18c
```

because that is the only way to write it.
